export const SKILLS_LIST = [
  'JavaScript',
  'TypeScript',
  'React',
  'Next.js',
  'Node.js',
  'Python',
  'Solidity',
  'Rust',
  'Go',
  'Java',
  'C++',
  'UI/UX Design',
  'Smart Contracts',
  'Blockchain',
  'Web3',
  'DevOps',
  'AI/ML',
  'Mobile Development',
  'Backend',
  'Frontend',
  'Full Stack',
  'Database',
  'Cloud',
  'Security',
  'Testing',
];

export const ROLE_OPTIONS = [
  'Frontend Developer',
  'Backend Developer',
  'Full Stack Developer',
  'Blockchain Developer',
  'Smart Contract Developer',
  'UI/UX Designer',
  'DevOps Engineer',
  'Data Scientist',
  'AI/ML Engineer',
  'Mobile Developer',
  'Project Manager',
  'Product Manager',
  'Technical Writer',
  'QA Engineer',
  'Marketing',
  'Business Developer',
];